name: test_project
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutterflow_ui: 0.3.1
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.0
  collection: 1.19.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.4
  path_provider: ^2.1.5
  path_provider_android: ^2.2.10
  path_provider_foundation: ^2.4.1
  path_provider_platform_interface: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  shared_preferences_android: ^2.3.2
  shared_preferences_foundation: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.2
  sqflite: ^2.3.3+1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.9
  url_launcher_ios: ^6.3.2
  url_launcher_platform_interface: 2.3.2
  simple_gradient_text: ^1.3.0
  page_transition: ^2.0.4
  pin_code_fields: 8.0.1
  smooth_page_indicator: ^1.0.1
  visibility_detector: ^0.4.0+2
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  file_picker: ^8.0.7
  video_player: 2.9.2
  video_player_web: ^2.3.3
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  just_audio_platform_interface: 4.3.0
  just_audio_web: ^0.4.13
  audio_session: ^0.1.23
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dependency_overrides: 
  http: ^0.13.0

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0


flutter_test:
  sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/videos/events/startingSequence/startingSequence.mp4
    - assets/videos/events/startingSequence/apartamentSeq/apartamentSeq.mp4
    - assets/videos/events/startingSequence/apartamentSeq/apartamentSeqSingle.mp4